export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const OBTENER_CHECKPOINTS = 'OBTENER_CHECKPOINTS';
export const AGREGAR_CHECKPOINT = 'AGREGAR_CHECKPOINT';
export const SALVAR_CHECKPOINT = 'SALVAR_CHECKPOINT';
export const VALIDAR_CHECKPOINT = 'VALIDAR_CHECKPOINT';
export const CHECKPOINT_ACTUAL = 'CHECKPOINT_ACTUAL';
export const ELIMINAR_CHECKPOINT = 'ELIMINAR_CHECKPOINT';
export const CHECKPOINT_ERROR = 'CHECKPOINT_ERROR';