export const OBTENER_CHECKPOINTS = 'OBTENER_CHECKPOINTS';
export const AGREGAR_CHECKPOINT = 'AGREGAR_CHECKPOINT';
export const VALIDAR_CHECKPOINT = 'VALIDAR_CHECKPOINT';
export const CHECKPOINT_ACTUAL = 'CHECKPOINT_ACTUAL';
export const ELIMINAR_CHECKPOINT = 'ELIMINAR_CHECKPOINT';